spring:
  application:
    name: transaction-service

  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 10000

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fintechwave_tx}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:29092}
    consumer:
      group-id: transaction-service
      key-deserializer:   org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer:   org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    listener:
      ack-mode: MANUAL_IMMEDIATE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  ${app.keycloak.issuer-uri}
          jwk-set-uri: ${app.keycloak.jwk-set-uri}

server:
  port: 8084
  error:
    include-message: never
    include-stacktrace: never

app:
  keycloak:
    issuer-uri: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8180}/realms/fintechwave
    jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/fintechwave/protocol/openid-connect/certs
    expected-audience: fintechwave-platform
  stripe:
    api-key:        ${STRIPE_API_KEY:sk_test_51Tg6jpFYLnavoJLBI9Wngbq7jwmmU2FsOztcX3VJWHKCa538C4K8u3VPb5p413UizHOjIZFx9Z3ikA7IQxQM0AGf00OpdNmv2X}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_4e48d4fec09ffb4c2fec97d4a600c5fdfeb83c5b033644b88fc3b503fc5f3e55}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    "[com.fintechwave.transaction]": DEBUG
    "[org.springframework.security]": INFO
    "[org.springframework.kafka]": INFO
    "[org.springframework.cloud.config]": INFO

grpc:
  client:
    ledger-service:
      address: 'dns:///${LEDGER_SERVICE_HOST:localhost}:9095'
      negotiation-type: plaintext