spring:
  application:
    name: transaction-service

  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 10000

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/fintechwave/protocol/openid-connect/certs}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fintechwave_tx}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8084
  error:
    include-message: never
    include-stacktrace: never

app:
  keycloak:
    jwk-set-uri: ${KEYCLOAK_URL:http://keycloak:8080}/realms/fintechwave/protocol/openid-connect/certs
    issuer-uri:  ${KEYCLOAK_URL:http://keycloak:8080}/realms/fintechwave

logging:
  level:
    "[com.fintechwave.transaction]": DEBUG
    "[org.springframework.security]": INFO
    "[org.springframework.cloud.config]": INFO
